version: "3.8"
services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    env_file: ./anothertest/.env
  app:
    build: ./anothertest/
    command: >
      sh -c "python3 manage.py makemigrations &&
             python3 manage.py migrate &&
             python3 manage.py createsuperuser --noinput &&
             python3 manage.py runserver 127.0.0.1:8000"
    ports:
      - "8000:8000"
    restart: on-failure
    depends_on:
      - db
    links: 
      - db
